### PR TITLE
Check the validity of the timezone

### PR DESCRIPTION
**Pull request by rgazelot**
1 - Catching invalid timezone from php's point of view. We met a case where Google sent us a Asia/Yangon timezone that isn't supported by DateTimeZone php object.
2 - Clean the typo of DateTime and DateTimeZone.

### CODE REVIEW

**Comment by rgazelot** [comment]
@krichprollsch Related to the timezone `Asia/Yangon` that Google gave.

**Review by krichprollsch — APPROVED** [review]
LGTM :+1:

**Comment by krichprollsch** [comment]
Hum after all I'm no sure it's good. A timezone like `GTM+02:00` is valid but with your changes you will ignore it...
Maybe try to build the `DateTimezone` and catching errors is a better way to go WDYT @rgazelot ?

**Review by krichprollsch — CHANGES_REQUESTED** [review]
see https://github.com/Calendart/GoogleAdapter/pull/15#issuecomment-255776872

**Comment by rgazelot** [comment]
hum indeed

**Comment by Taluu** [comment]
Yup, a try / catch should be more than enough.

BTW, please add more context next time on the first message, so I have a clue of what is going on without having to read everything and the code... Especially when it is mixed with changes on `DateTime` (even though these are correct).

**Comment by rgazelot** [comment]
@krichprollsch @Taluu Modifications done.

**Pull request merged**
